blogs/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, CommentCreateView

app_name = 'blogs'

urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('<int:pk>/post/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('pages.urls')),
    path('', include('users.urls')),
    path('shop/', include('shop.urls')),
    path('blogs/', include('blogs.urls')),
    path('', include('orders.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import OrderHistoryView, CheckoutView

app_name = 'orders'

urlpatterns = [
    path('order/history/', OrderHistoryView.as_view(), name='history'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, ContactView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
]

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView, wishlist_view, WishListView, update_cart_view, ShoppingCart

app_name = 'shop'

urlpatterns = [
    path('', ShopView.as_view(), name='home'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('product/<int:pk>/wishlist/', wishlist_view, name='wishlist'),
    path('wishlists/', WishListView.as_view(), name='all_wishlists'),
    path('add_cart/<int:id>/', update_cart_view, name='cart'),
    path('shopping_cart/', ShoppingCart.as_view(), name='shopping-cart')
]

users/urls.py
from django.urls import path
from .views import login_view, user_registration, logout_view, ProfileView

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('registration/', user_registration, name='registration'),
    path('logout/', logout_view, name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

blogs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField


class AutherModel(models.Model):
    full_name = models.CharField(max_length=100, verbose_name=_('full_name'))
    image = models.ImageField(upload_to='auther_images/', verbose_name=_('image'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('auther')
        verbose_name_plural = _('authers')


class PostTagModel(models.Model):
    name = models.CharField(max_length=30, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class PostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    body = RichTextUploadingField(verbose_name=_('body'))
    main_image = models.ImageField(upload_to='main_images/', verbose_name=_('main image'))
    banner = models.ImageField(upload_to='post_banners/', verbose_name=_('banner'))
    auther = models.ForeignKey(AutherModel, related_name='posts', on_delete=models.RESTRICT, verbose_name='auther')
    tag = models.ManyToManyField(PostTagModel, related_name='posts', verbose_name=_('tag'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return f"{self.title[:100]} ..."

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')


class CommentModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    phone = models.CharField(max_length=13, verbose_name=_('phone'))
    comment = models.TextField(verbose_name=_('comment'))
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE, related_name='comments', verbose_name=_('post'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return f"{self.name}\n{self.email}\n{self.phone}\n{self.comment}"

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

shop/models.py
from django.contrib.auth import get_user_model
from django.db.models import Sum
from django.utils import timezone
from django.db import models, IntegrityError
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField

UserModel = get_user_model()


class CategoryModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class ProductTagModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class BrandModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'


class SizeModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'size'
        verbose_name_plural = 'sizes'


class ColorModel(models.Model):
    code = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'color'
        verbose_name_plural = 'colors'


class ProductModel(models.Model):
    title = models.CharField(max_length=60, verbose_name=_('title'))
    short_description = models.CharField(max_length=255, verbose_name=_('short description'))
    long_description = RichTextUploadingField(verbose_name=_('long description'))
    price = models.FloatField(verbose_name=_('price'))
    real_price = models.FloatField(verbose_name=_('real price'), default=0)
    sale = models.BooleanField(verbose_name=_('sale'), default=False)
    discount = models.PositiveSmallIntegerField(default=0, verbose_name=_('discount'))
    main_image = models.ImageField(upload_to='products', verbose_name=_('main image'))
    category = models.ForeignKey(
        CategoryModel,
        related_name='products',
        on_delete=models.RESTRICT,
        verbose_name=_('category')
    )
    tags = models.ManyToManyField(
        ProductTagModel,
        related_name='products',
        verbose_name=_('tags')
    )
    sizes = models.ManyToManyField(
        SizeModel,
        related_name='products',
        verbose_name=_('sizes')
    )
    colors = models.ManyToManyField(
        ColorModel,
        related_name='products',
        verbose_name=_('colors')
    )
    brands = models.ForeignKey(
        BrandModel,
        on_delete=models.RESTRICT,
        related_name='products',
        verbose_name=_('brands'),
        null=True
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def is_discount(self):
        return bool(self.discount)

    def new(self):
        return (timezone.now() - self.created_at).days <= 5

    @staticmethod
    def get_cart_info(request):
        cart = request.session.get('cart', [])
        if not cart:
            return 0, 0.0
        return len(cart), ProductModel.objects.filter(id__in=cart).aggregate(Sum('real_price'))['real_price__sum']

    @staticmethod
    def get_cart_objects(request):
        cart = request.session.get('cart', [])
        if not cart:
            return None
        return ProductModel.objects.filter(id__in=cart)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'


class WishListModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='wishlists', verbose_name=_('user'))
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, verbose_name=_('product'))

    @staticmethod
    def create_or_delete(user, product):
        try:
            return WishListModel.objects.create(user=user, product=product)
        except IntegrityError:
            return WishListModel.objects.get(user=user, product=product).delete()

    def __str__(self):
        return f"{self.user.get_full_name()} | {self.product.title}"

    class Meta:
        verbose_name = 'wishlist'
        verbose_name_plural = 'wishlists'
        unique_together = 'user', 'product'

blogs/forms.py
from django import forms
from .models import CommentModel

class CommentModelForm(forms.ModelForm):

    class Meta:
        model = CommentModel
        exclude = ['created_at', 'post']

shop/forms.py
from django import forms
from .models import ColorModel


class ColorModelAdminForms(forms.ModelForm):
    code = forms.CharField(widget=forms.TextInput(attrs={'type': 'color'}))

    class Meta:
        model = ColorModel
        fields = '__all__'

blogs/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from .models import PostModel
from .forms import CommentModelForm


class PostListView(ListView):
    template_name = 'blog.html'

    def get_queryset(self):
        qs = PostModel.objects.order_by('-id')
        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tag__name=tag)
        return qs


class PostDetailView(DetailView):
    model = PostModel
    template_name = 'blog-detail.html'


class CommentCreateView(CreateView):
    form_class = CommentModelForm

    def form_valid(self, form):
        print(form.instance)
        form.instance.post = get_object_or_404(PostModel, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogs:detail', kwargs={'pk': self.kwargs.get('pk')})

shop/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Min, Max
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from .models import ProductModel, CategoryModel, ProductTagModel, ColorModel, BrandModel, SizeModel, WishListModel


class ShopView(ListView):
    template_name = 'shop.html'
    paginate_by = 3

    def get_queryset(self):
        qs = ProductModel.objects.all()

        search = self.request.GET.get('search')
        if search:
            qs = qs.filter(title__icontains=search)

        cat = self.request.GET.get('cat')
        if cat:
            qs = qs.filter(category_id=cat)

        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tags=tag)

        size = self.request.GET.get('size')
        if size:
            qs = qs.filter(sizes=size)

        color = self.request.GET.get('color')
        if color:
            qs = qs.filter(colors=color)

        brand = self.request.GET.get('brand')
        if brand:
            qs = qs.filter(brands=brand)

        sort = self.request.GET.get('sort')
        if sort == 'price':
            qs = qs.order_by('price')
        elif sort == '-price':
            qs = qs.order_by('-price')
        elif sort == 'sale':
            qs = qs.filter(sale=True)

        price = self.request.GET.get('price')
        if price:
            min, max = price.split(';')
            qs = qs.filter(real_price__gte=min, real_price__lte=max)

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        data['categories'] = CategoryModel.objects.all()
        data['tags'] = ProductTagModel.objects.all()
        data['sizes'] = SizeModel.objects.all()
        data['brands'] = BrandModel.objects.all()
        data['colors'] = ColorModel.objects.all()
        data['min_price'], data['max_price'] = ProductModel.objects.aggregate(Min('real_price'),
                                                                              Max('real_price')).values()
        return data


class ProductDetailView(DetailView):
    model = ProductModel
    template_name = 'shop-detail.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        data['products'] = ProductModel.objects.all().exclude(id=self.object.pk)[:4]
        return data


@login_required
def wishlist_view(request, pk):
    product = get_object_or_404(ProductModel, pk=pk)
    WishListModel.create_or_delete(request.user, product)
    return redirect(request.GET.get('next', '/'))


class WishListView(LoginRequiredMixin, ListView):
    template_name = 'wishlist.html'

    def get_queryset(self):
        return ProductModel.objects.filter(wishlistmodel__user_id=self.request.user)


def update_cart_view(request, id):
    cart = request.session.get('cart', [])
    print(request.session.get('cart', []))

    if id in cart:
        cart.remove(id)
    else:
        cart.append(id)

    request.session['cart'] = cart
    return redirect(request.GET.get('next', '/'))


class ShoppingCart(ListView):
    template_name = 'shopping-cart.html'

    def get_queryset(self):
        products = ProductModel.get_cart_objects(self.request)
        return products

templates/blog-detail.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

<!-- Blog Details Hero Begin -->
<section class="blog-hero spad">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-9 text-center">
                <div class="blog__hero__text">
                    <h2>{{ object.title }}</h2>
                    <ul>
                        <li>{{ object.auther.full_name }}</li>
                        <li>{{ object.created_at|date:"F d, Y" }}</li>
                        {% if object.comments.values%}
                        <li>{{ object.comments.values.count }} Comments</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Details Hero End -->

<!-- Blog Details Section Begin -->
<section class="blog-details spad">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="blog__details__pic">
                    <img src="{{ object.banner.url }}" alt="{{ object.title }}">
                </div>
            </div>
            <div class="col-lg-8">
                <div class="blog__details__content">
                    <div class="blog__details__share">
                        <span>share</span>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                            <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                    <div class="blog__details__text">
                        {{object.body|safe }}
                    </div>
                    <div class="blog__details__quote">
                        <i class="fa fa-quote-left"></i>
                        <p>“When designing an advertisement for a particular product many things should be
                            researched like where it should be displayed.”</p>
                        <h6>_ John Smith _</h6>
                    </div>
                    <div class="blog__details__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="blog__details__author">
                                    <div class="blog__details__author__pic">
                                        <img src="{{ object.auther.image.url }}" alt="{{ object.auther.full_name }}">
                                    </div>
                                    <div class="blog__details__author__text">
                                        <h5>{{ object.auther.full_name }}</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="blog__details__tags">
                                    {% for tag in object.tag.values %}
                                    <a href="{% url 'blogs:posts' %}?tag={{ tag.name }}">#{{ tag.name }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="blog__details__btns">
                        <div class="row">
                            {% if object.get_next_by_created_at %}
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <a href="{% url 'blogs:detail' pk=object.get_next_by_created_at.pk %}"
                                   class="blog__details__btns__item">
                                    <p><span class="arrow_left"></span> Previous Pod</p>
                                    <h5>{{ object.get_next_by_created_at.title }}</h5>
                                </a>
                            </div>
                            {% endif %}
                            {% if object.get_previous_by_created_at %}
                            <div class="col-lg-6 col-md-6 col-sm-6 {% if not object.get_next_by_created_at %}offset-6{% endif %}">
                                <a href="{% url 'blogs:detail' pk=object.get_previous_by_created_at.pk %}" class="blog__details__btns__item blog__details__btns__item--next">
                                    <p>Next Pod <span class="arrow_right"></span></p>
                                    <h5>{{ object.get_previous_by_created_at.title }}</h5>
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="container">
                        {% for comment in object.comments.values %}
                        <div class="row mb-3">
                            <div class="col-6 "><strong>{{ comment.name }}</strong></div>
                            <div class="col-6 text-right">{{ comment.created_at|timesince }}</div>
                            <div class="col-12 mt-2">
                                <p>
                                    {{ comment.comment }}
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="blog__details__comment">
                        <h4>Leave A Comment</h4>
                        <form action="{% url 'blogs:comment' pk=object.pk %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-4 col-md-4">
                                    <input name="name" type="text" placeholder="Name">
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <input name="email" type="text" placeholder="Email">
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <input name="phone" type="text" placeholder="Phone">
                                </div>
                                <div class="col-lg-12 text-center">
                                    <textarea name="comment" placeholder="Comment"></textarea>
                                    <button type="submit" class="site-btn">Post Comment</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Details Section End -->
{% endblock %}

templates/contact.html
{% extends 'layouts/base.html' %}
{% block content %}

    <!-- Map Begin -->
    <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d111551.9926412813!2d-90.27317134641879!3d38.606612219170856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited%20States!5e0!3m2!1sen!2sbd!4v1597926938024!5m2!1sen!2sbd" height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
    <!-- Map End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="contact__text">
                        <div class="section-title">
                            <span>Information</span>
                            <h2>Contact Us</h2>
                            <p>As you might expect of a company that began as a high-end interiors contractor, we pay
                                strict attention.</p>
                        </div>
                        <ul>
                            <li>
                                <h4>America</h4>
                                <p>195 E Parker Square Dr, Parker, CO 801 <br />+43 982-314-0958</p>
                            </li>
                            <li>
                                <h4>France</h4>
                                <p>109 Avenue Léon, 63 Clermont-Ferrand <br />+12 345-423-9893</p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="contact__form">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6">
                                    <input name="name" type="text" placeholder="Name">
                                </div>
                                <div class="col-lg-6">
                                    <input name="email" type="email" placeholder="Email">
                                </div>
                                <div class="col-lg-12">
                                    <textarea name="message" placeholder="Message"></textarea>
                                    <button type="submit" class="site-btn">Send Message</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->
{% endblock %}

templates/registrations.html
{% extends "layouts/base-login.html" %}
{% load static i18n crispy_forms_tags %}

{% block content %}
<div class="d-md-flex half">
    <div class="bg" style="background-image: url({% static 'img/bg_1.jpg' %});"></div>
    <div class="contents">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-12">
                    <div class="form-block mx-auto">
                        <div class="text-center mb-5">
                            <h3 class="text-uppercase">Registration</h3>
                        </div>
                        <form action="{% url 'user:registration' %}" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
<!--                            <div class="form-group first">-->
<!--                                <label for="username">Username</label>-->
<!--                                {{form.username}}-->
<!--                                <span class="text-danger">{{form.errors.username}}</span>-->
<!--                            </div>-->
<!--                            <div class="form-group first">-->
<!--                                <label for="phone">Phone number</label>-->
<!--                                {{form.phone_number}}-->
<!--                            </div>-->
<!--                            <div class="form-group last mb-3">-->
<!--                                <label for="password">Password</label>-->
<!--                                {{form.password}}-->
<!--                            </div>-->
<!--                            <div class="form-group last mb-3">-->
<!--                                <label for="confirm_password">Confirm Password</label>-->
<!--                                {{form.confirm_password}}-->
<!--                                <span class="text-danger">{{form.errors.confirm_password}}</span>-->
<!--                            </div>-->

                            <div class="d-sm-flex mb-5 align-items-center">
                                <label class="control control--checkbox mb-3 mb-sm-0"><span
                                        class="caption">Remember me</span>
                                    <input type="checkbox" checked="checked"/>
                                    <div class="control__indicator"></div>
                                </label>
                                <span class="ml-auto"><a href="{% url 'user:login' %}"
                                                         class="forgot-pass">Login</a></span>
                            </div>

                            <input type="submit" value="Save" class="btn btn-block py-2 btn-primary">

                            <span class="text-center my-3 d-block">or</span>


                            <div class="">
                                <a href="#" class="btn btn-block py-2 btn-facebook">
                                    <span class="icon-facebook mr-3"></span> Login with facebook
                                </a>
                                <a href="#" class="btn btn-block py-2 btn-google"><span class="icon-google mr-3"></span>
                                    Login with Google</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/shopping-cart.html
{% extends 'layouts/base.html' %}
{% load static my_tags %}

{% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Shopping Cart</h4>
                    <div class="breadcrumb__links">
                        <a href="./index.html">Home</a>
                        <a href="./shop.html">Shop</a>
                        <span>Shopping Cart</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Shopping Cart Section Begin -->
<section class="shopping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="shopping__cart__table">
                    <table>
                        <thead>
                        <tr>
                            <th>Product</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in object_list %}
                        <tr>
                            <td class="product__cart__item">
                                <div class="product__cart__item__pic">
                                    <img src="{{product.main_image.url}}" alt="">
                                </div>
                                <div class="product__cart__item__text">
                                    <h6>T-shirt Contrast Pocket</h6>
                                    <h5>${{product.real_price}}</h5>
                                </div>
                            </td>
                            <td class="quantity__item">
                                <div class="quantity">
                                    <div class="pro-qty-2">
                                        <input type="text" value="1">
                                    </div>
                                </div>
                            </td>
                            <td class="cart__price">$ {{product.real_price}}</td>
                            <td class="cart__close">
                                <a href="{% url 'shop:cart' id=product.pk %}?next={{ request.path }}" class="add-cart">
                                    {% if product|is_cart:request %}
                                        <i class="fa fa-close"></i>
                                    {% endif %}
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart__discount">
                    <h6>Discount codes</h6>
                    <form action="#">
                        <input type="text" placeholder="Coupon code">
                        <button type="submit">Apply</button>
                    </form>
                </div>
                <div class="cart__total">
                    <h6>Cart total</h6>
                    <ul>
                        <hr>
                        {% cart_info request as info %}
                        <!--                            <li>Subtotal <span>$ {{info.1}}</span></li>-->
                        <li>Total <span>$ {{info.1}}</span></li>
                    </ul>
                    <a href="{% url 'orders:checkout' %}" class="primary-btn">Proceed to checkout</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shopping Cart Section End -->
{% endblock %}